name: fc_frontend
description: Collaborative tool using AppFlowyEditor
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  appflowy_editor:
    git:
      url: https://github.com/AppFlowy-IO/appflowy-editor
      ref: main
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0
  get_it: ^7.3.0
  http: ^0.13.5
  injectable: ^2.1.1
  json_annotation: ^4.8.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - .env
